# Datenaufbereitung für Ground Trouth Datensatz

In [1]:
# Imports 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Pakages
!pip install pandas openpyxl numpy matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy in C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (2.4.4)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2026.1)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.62.1-cp312-cp312-win_amd64.whl.metadata (119 kB)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp312-cp312-win_amd64.whl (2.3 MB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: fonttools, et-xmlfile, cycler, contourpy, pandas, openpyxl, matplotlib, seaborn

   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ---------------------------------------- 0/8 [fonttools]
   ----- ---------------------------------- 1/8 [et-xmlfile]
   --------------- ------------------------ 3/8 [contourpy]
   --------------- ------------------------ 3/8 [contourpy]
   --------------- ------------------------ 3/8 [contourpy]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------- -------------- 5/8 [openpyxl]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 et-xmlfile-2.0.0 fonttools-4.62.1 matplotlib-3.10.8 openpyxl-3.1.5 pandas-3.0.2 seaborn-0.13.2

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\Startklar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [2]:
# Daten einlesen

df = pd.read_excel("Adressen_Winti_Dep_Arch.xlsx")
df.head()

,EGID,GEB_GEBID,GSW_STATUS,STRASSENNAME,HAUSNR,HAUSNRZUSATZ,PLZ4,ORT,STADTKREIS,HAUPTNUTZUNG,...,Fläche,Speziell,Fläche10,Holz,Holz Lm,Fläche11,Extra,Unnamed: 52,Unnamed: 53,Unnamed: 54
0,210294075,35999,bestehend,Albert-Einstein-Strasse,1,0,8404,Winterthur,Oberwinterthur,Industrie und Gerwerbe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,191993323,36666,bestehend,Schützenwiesenweg,8,0,8400,Winterthur,Winterthur-Stadt,Verwaltungsgebäude und Gebäude mit öffentliche...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,191975144,34926,im Bau,Sporrerpark,2,0,8408,Winterthur,Wülflingen,Nebengebäude und dev.Gebäude,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,191975148,34924,im Bau,Sporrerpark,5,0,8408,Winterthur,Wülflingen,Wohngebäude,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,191975148,34924,im Bau,Sporrerpark,4,0,8408,Winterthur,Wülflingen,Wohngebäude,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Daten anzeigen

print(df.shape)
print(df.columns)
df.info()

(846, 55)
Index(['EGID', 'GEB_GEBID', 'GSW_STATUS', 'STRASSENNAME', 'HAUSNR',
       'HAUSNRZUSATZ', 'PLZ4', 'ORT', 'STADTKREIS', 'HAUPTNUTZUNG', 'NUTZUNG',
       'GS_EIGENTUMSKATEGORIE', 'GS_EIGENTUMSKAT_ZUSATZ', 'BAUJAHR', 'Spalte2',
       'Reale Baujahr', 'Spalte3', 'Link Google', 'Spalte4', 'Schadstoffen',
       'Tragwerk Fassade6', 'Fassade Dämmung', 'zus. Eigenschaften 1',
       'zus. Eigenschaften 2', 'Fassade Bekleidung', 'Konstruktion Decke',
       'Bodenaufbau', 'Konstruktion Dach', 'Dach Bekleidung', 'Photovoltaik',
       'PV Fläche', 'Fenster', 'Fensteranzahl', 'Dämmungsfläche', 'Stahl',
       'Stahl lm', 'Stahlblech', 'Fläche ', 'Eternit', 'Fläche 7',
       'Steinplatten', 'Fläche 8', 'Dachziegel', 'Fläche 9', 'Beton', 'Fläche',
       'Speziell', 'Fläche10', 'Holz', 'Holz Lm', 'Fläche11', 'Extra',
       'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 55 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EGID                    846 non-null    int64
 1   GEB_GEBID               846 non-null    int64
 2   GSW_STATUS              846 non-null    object
 3   STRASSENNAME            846 non-null    object
 4   HAUSNR                  846 non-null    int64
 5   HAUSNRZUSATZ            846 non-null    object
 6   PLZ4                    846 non-null    int64
 7   ORT                     846 non-null    object
 8   STADTKREIS              846 non-null    object
 9   HAUPTNUTZUNG            846 non-null    object
 10  NUTZUNG                 846 non-null    object
 11  GS_EIGENTUMSKATEGORIE   846 non-null    object
 12  GS_EIGENTUMSKAT_ZUSATZ  846 non-null    object
 13  BAUJAHR                 846 non-null    int64
 14  Spalte2                 0 non-null      float64
 15  Reale Baujahr           46 non-null     object
 16  Spalte3                 0 non-null      float64
 17  Link Google             451 non-null    object
 18  Spalte4                 1 non-null      float64
 19  Schadstoffen            494 non-null    object
 20  Tragwerk Fassade6       725 non-null    object
 21  Fassade Dämmung         700 non-null    object
 22  zus. Eigenschaften 1    0 non-null      float64
 23  zus. Eigenschaften 2    1 non-null      object
 24  Fassade Bekleidung      445 non-null    object
 25  Konstruktion Decke      449 non-null    object
 26  Bodenaufbau             667 non-null    object
 27  Konstruktion Dach       448 non-null    object
 28  Dach Bekleidung         706 non-null    object
 29  Photovoltaik            710 non-null    object
 30  PV Fläche               33 non-null     object
 31  Fenster                 750 non-null    object
 32  Fensteranzahl           121 non-null    float64
 33  Dämmungsfläche          116 non-null    float64
 34  Stahl                   119 non-null    object
 35  Stahl lm                119 non-null    float64
 36  Stahlblech              118 non-null    object
 37  Fläche                  116 non-null    float64
 38  Eternit                 118 non-null    object
 39  Fläche 7                118 non-null    object
 40  Steinplatten            118 non-null    object
 41  Fläche 8                118 non-null    float64
 42  Dachziegel              118 non-null    object
 43  Fläche 9                118 non-null    float64
 44  Beton                   118 non-null    object
 45  Fläche                  116 non-null    object
 46  Speziell                117 non-null    object
 47  Fläche10                118 non-null    object
 48  Holz                    35 non-null     object
 49  Holz Lm                 35 non-null     float64
 50  Fläche11                26 non-null     float64
 51  Extra                   117 non-null    object
 52  Unnamed: 52             2 non-null      object
 53  Unnamed: 53             1 non-null      float64
 54  Unnamed: 54             1 non-null      object
dtypes: float64(13), int64(5), object(37)
memory usage: 363.6+ KB

In [4]:
# Spaltennamen anzeigen
print(df.columns)

Index(['EGID', 'GEB_GEBID', 'GSW_STATUS', 'STRASSENNAME', 'HAUSNR',
       'HAUSNRZUSATZ', 'PLZ4', 'ORT', 'STADTKREIS', 'HAUPTNUTZUNG', 'NUTZUNG',
       'GS_EIGENTUMSKATEGORIE', 'GS_EIGENTUMSKAT_ZUSATZ', 'BAUJAHR', 'Spalte2',
       'Reale Baujahr', 'Spalte3', 'Link Google', 'Spalte4', 'Schadstoffen',
       'Tragwerk Fassade6', 'Fassade Dämmung', 'zus. Eigenschaften 1',
       'zus. Eigenschaften 2', 'Fassade Bekleidung', 'Konstruktion Decke',
       'Bodenaufbau', 'Konstruktion Dach', 'Dach Bekleidung', 'Photovoltaik',
       'PV Fläche', 'Fenster', 'Fensteranzahl', 'Dämmungsfläche', 'Stahl',
       'Stahl lm', 'Stahlblech', 'Fläche ', 'Eternit', 'Fläche 7',
       'Steinplatten', 'Fläche 8', 'Dachziegel', 'Fläche 9', 'Beton', 'Fläche',
       'Speziell', 'Fläche10', 'Holz', 'Holz Lm', 'Fläche11', 'Extra',
       'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54'],
      dtype='object')

In [5]:
# Spaltennamen 'EGID', 'GEB_GEBID', 'STRASSENNAME', 'HAUSNR', 'HAUSNRZUSATZ', 'PLZ4', 'ORT', 'STADTKREIS', 'HAUPTNUTZUNG' auswählen und in neuem df speichern
df_selected = df[['EGID', 'GEB_GEBID', 'STRASSENNAME', 'HAUSNR', 'HAUSNRZUSATZ', 'PLZ4', 'ORT', 'STADTKREIS', 'HAUPTNUTZUNG']]

# df_selected anzeigen
df_selected.head()

,EGID,GEB_GEBID,STRASSENNAME,HAUSNR,HAUSNRZUSATZ,PLZ4,ORT,STADTKREIS,HAUPTNUTZUNG
0,210294075,35999,Albert-Einstein-Strasse,1,0,8404,Winterthur,Oberwinterthur,Industrie und Gerwerbe
1,191993323,36666,Schützenwiesenweg,8,0,8400,Winterthur,Winterthur-Stadt,Verwaltungsgebäude und Gebäude mit öffentliche...
2,191975144,34926,Sporrerpark,2,0,8408,Winterthur,Wülflingen,Nebengebäude und dev.Gebäude
3,191975148,34924,Sporrerpark,5,0,8408,Winterthur,Wülflingen,Wohngebäude
4,191975148,34924,Sporrerpark,4,0,8408,Winterthur,Wülflingen,Wohngebäude

In [6]:
# df_selected Spalte Hauptnutzung analysieren und Häufigkeit der Werte anzeigen
print(df_selected['HAUPTNUTZUNG'].value_counts())

HAUPTNUTZUNG
Verwaltungsgebäude und Gebäude mit öffentlichem Charakter    348
Wohngebäude                                                  303
Industrie und Gerwerbe                                        83
0                                                             38
Landwirtschaft, Gärtnerei und Forstwirtschaft                 26
Nebengebäude und dev.Gebäude                                  17
Verkehrswesen                                                 15
Handel                                                        12
Gastgewerbe                                                    4
Name: count, dtype: int64

In [7]:
# Neues df aus df_selected erstellen, nur mit den Zeilen, in denen Hauptnutzung == 'Verwaltungsgebäude und Gebäude mit öffentlichem Charakter' oder 'Wohngebäude' ist
df_filtered = df_selected[df_selected['HAUPTNUTZUNG'].isin(['Verwaltungsgebäude und Gebäude mit öffentlichem Charakter', 'Wohngebäude'])]

# df_filtered anzeigen
print(df_filtered.head())

# Anzahl der Zeilen in df_filtered anzeigen
print(df_filtered.shape[0])

        EGID  GEB_GEBID       STRASSENNAME  HAUSNR HAUSNRZUSATZ  PLZ4  \
1  191993323      36666  Schützenwiesenweg       8            0  8400
3  191975148      34924        Sporrerpark       5            0  8408
4  191975148      34924        Sporrerpark       4            0  8408
6  210215067      33882   Grüzefeldstrasse      34            0  8400
7  210261475      35794  Guggenbühlstrasse     140            a  8404

          ORT        STADTKREIS  \
1  Winterthur  Winterthur-Stadt
3  Winterthur        Wülflingen
4  Winterthur        Wülflingen
6  Winterthur        Mattenbach
7  Winterthur    Oberwinterthur

                                        HAUPTNUTZUNG
1  Verwaltungsgebäude und Gebäude mit öffentliche...
3                                        Wohngebäude
4                                        Wohngebäude
6  Verwaltungsgebäude und Gebäude mit öffentliche...
7  Verwaltungsgebäude und Gebäude mit öffentliche...
651

In [8]:
# 6 Zeilen mit Hauptnutzung 'Verwaltungsgebäude und Gebäude mit öffentlichem Charakter' und 6 Zeilen mit Hauptnutzung 'Wohngebäude' in neuem df speichern
df_final = df_filtered[df_filtered['HAUPTNUTZUNG'].isin(['Verwaltungsgebäude und Gebäude mit öffentlichem Charakter', 'Wohngebäude'])].groupby('HAUPTNUTZUNG').head(6)

# df_final anzeigen
print(df_final)

         EGID  GEB_GEBID       STRASSENNAME  HAUSNR HAUSNRZUSATZ  PLZ4  \
1   191993323      36666  Schützenwiesenweg       8            0  8400
3   191975148      34924        Sporrerpark       5            0  8408
4   191975148      34924        Sporrerpark       4            0  8408
6   210215067      33882   Grüzefeldstrasse      34            0  8400
7   210261475      35794  Guggenbühlstrasse     140            a  8404
8   191953253      36289      Hörnlistrasse      31            0  8400
9   191953634      36291        Im Hölderli       3            0  8405
10  191980305      36569        Kiesstrasse       4            0  8400
17  210222195      35083        Sulzerallee      76            0  8404
18  210222195      35083        Sulzerallee      72            0  8404
19  210222195      35083        Sulzerallee      74            0  8404
47  210217184      34546  Wülflingerstrasse     263            a  8408

           ORT        STADTKREIS  \
1   Winterthur  Winterthur-Stadt
3   Winterthur        Wülflingen
4   Winterthur        Wülflingen
6   Winterthur        Mattenbach
7   Winterthur    Oberwinterthur
8   Winterthur        Mattenbach
9   Winterthur              Seen
10  Winterthur  Winterthur-Stadt
17  Winterthur    Oberwinterthur
18  Winterthur    Oberwinterthur
19  Winterthur    Oberwinterthur
47  Winterthur        Wülflingen

                                         HAUPTNUTZUNG
1   Verwaltungsgebäude und Gebäude mit öffentliche...
3                                         Wohngebäude
4                                         Wohngebäude
6   Verwaltungsgebäude und Gebäude mit öffentliche...
7   Verwaltungsgebäude und Gebäude mit öffentliche...
8   Verwaltungsgebäude und Gebäude mit öffentliche...
9   Verwaltungsgebäude und Gebäude mit öffentliche...
10  Verwaltungsgebäude und Gebäude mit öffentliche...
17                                        Wohngebäude
18                                        Wohngebäude
19                                        Wohngebäude
47                                        Wohngebäude

In [9]:
# df_final als Excel-Datei speichern
df_final.to_excel("Datenanalyse_Ergebnis.xlsx", index=False)