# Aufbereitung der analysierten Daten

In [116]:
# Imports
from pathlib import Path
import pandas as pd
import numpy as np

# Pfad zum Data-Ordner
data_dir = Path("Data")

In [117]:
# Excel aus Notebook 2 einlesen
df = pd.read_excel(data_dir / "02_API_Baujahr_Adressen.xlsx").copy()

print("Shape:", df.shape)
print("\nSpalten:")
print(df.columns.tolist())

display(df.head())

Shape: (814, 66)

Spalten:
['EGID', 'GEB_GEBID', 'GSW_STATUS', 'STRASSENNAME', 'HAUSNR', 'HAUSNRZUSATZ', 'PLZ4', 'ORT', 'STADTKREIS', 'HAUPTNUTZUNG', 'NUTZUNG', 'GS_EIGENTUMSKATEGORIE', 'GS_EIGENTUMSKAT_ZUSATZ', 'BAUJAHR', 'Spalte2', 'Reale Baujahr', 'Spalte3', 'Link Google', 'Spalte4', 'Schadstoffen', 'Tragwerk Fassade6', 'Fassade Dämmung', 'zus. Eigenschaften 1', 'zus. Eigenschaften 2', 'Fassade Bekleidung', 'Konstruktion Decke', 'Bodenaufbau', 'Konstruktion Dach', 'Dach Bekleidung', 'Photovoltaik', 'PV Fläche', 'Fenster', 'Fensteranzahl', 'Dämmungsfläche', 'Stahl', 'Stahl lm', 'Stahlblech', 'Fläche ', 'Eternit', 'Fläche 7', 'Steinplatten', 'Fläche 8', 'Dachziegel', 'Fläche 9', 'Beton', 'Fläche', 'Speziell', 'Fläche10', 'Holz', 'Holz Lm', 'Fläche11', 'Extra', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'adresse_api', 'feature_id', 'egid_gwr', 'baujahr_gwr', 'label_api', 'x_api', 'y_api', 'lat_api', 'lon_api', 'status_api', 'baujahr_gleich']

,EGID,GEB_GEBID,GSW_STATUS,STRASSENNAME,HAUSNR,HAUSNRZUSATZ,PLZ4,ORT,STADTKREIS,HAUPTNUTZUNG,...,feature_id,egid_gwr,baujahr_gwr,label_api,x_api,y_api,lat_api,lon_api,status_api,baujahr_gleich
0,210294075,35999,bestehend,Albert-Einstein-Strasse,1,0,8404,Winterthur,Oberwinterthur,Industrie und Gerwerbe,...,210294075_0,210294075,2024,Albert-Einstein-Strasse 1 <b>8404 Winterthur</b>,1263647.750,2700009.75,47.515961,8.766397,OK,True
1,191993323,36666,bestehend,Schützenwiesenweg,8,0,8400,Winterthur,Winterthur-Stadt,Verwaltungsgebäude und Gebäude mit öffentliche...,...,191993323_0,191993323,2024,Schützenwiesenweg 8 <b>8400 Winterthur</b>,1261888.125,2696149.25,47.500713,8.714772,OK,True
2,191975144,34926,im Bau,Sporrerpark,2,0,8408,Winterthur,Wülflingen,Nebengebäude und dev.Gebäude,...,191975144_0,191975144,2024,Sporrerpark 2 <b>8408 Winterthur</b>,1263772.625,2694387.25,47.517914,8.691791,OK,True
3,191975148,34924,im Bau,Sporrerpark,5,0,8408,Winterthur,Wülflingen,Wohngebäude,...,191975148_1,191975148,2024,Sporrerpark 5 <b>8408 Winterthur</b>,1263791.000,2694430.75,47.518074,8.692369,OK,True
4,191975148,34924,im Bau,Sporrerpark,4,0,8408,Winterthur,Wülflingen,Wohngebäude,...,191975148_0,191975148,2024,Sporrerpark 4 <b>8408 Winterthur</b>,1263792.375,2694416.25,47.518089,8.692179,OK,True

In [118]:
# Grundlegende Datenübersicht visualisieren

print("Datentypen:")
display(df.dtypes.to_frame("dtype"))

print("\nFehlende Werte pro Spalte:")
display(df.isna().sum().sort_values(ascending=False).to_frame("fehlende_werte"))

print("\nAnzahl eindeutige Werte pro Spalte:")
display(df.nunique(dropna=False).sort_values(ascending=False).to_frame("anzahl_eindeutige_werte"))

# Erste deskriptive Übersicht für numerische Spalten
print("\nDeskriptive Statistik (numerische Spalten):")
display(df.describe(include="number").T)

# Deskriptive Übersicht für Text-/Kategorie-Spalten
print("\nDeskriptive Statistik (Objekt-/Kategorie-Spalten):")
display(df.describe(include="object").T)

Datentypen:

                  dtype
EGID              int64
GEB_GEBID         int64
GSW_STATUS       object
STRASSENNAME     object
HAUSNR            int64
...                 ...
y_api           float64
lat_api         float64
lon_api         float64
status_api       object
baujahr_gleich     bool

[66 rows x 1 columns]

Fehlende Werte pro Spalte:

                      fehlende_werte
Spalte3                          814
Spalte2                          814
zus. Eigenschaften 1             814
Unnamed: 54                      813
zus. Eigenschaften 2             813
...                              ...
y_api                              0
lat_api                            0
lon_api                            0
status_api                         0
baujahr_gleich                     0

[66 rows x 1 columns]

Anzahl eindeutige Werte pro Spalte:

                      anzahl_eindeutige_werte
feature_id                                813
label_api                                 813
adresse_api                               813
lon_api                                   810
x_api                                     801
...                                       ...
Spalte2                                     1
zus. Eigenschaften 1                        1
Spalte3                                     1
status_api                                  1
baujahr_gleich                              1

[66 rows x 1 columns]

Deskriptive Statistik (numerische Spalten):

,count,mean,std,min,25%,50%,75%,max
EGID,814.0,7.743865e+07,9.776475e+07,1.150006e+06,1.156496e+06,2.325051e+06,2.010326e+08,2.102941e+08
GEB_GEBID,814.0,1.723917e+04,1.034489e+04,1.070000e+02,9.926000e+03,1.490800e+04,2.732075e+04,3.706800e+04
HAUSNR,814.0,4.192998e+01,5.833513e+01,1.000000e+00,8.000000e+00,2.000000e+01,5.100000e+01,4.090000e+02
PLZ4,814.0,8.403543e+03,6.586355e+00,8.310000e+03,8.400000e+03,8.404000e+03,8.406000e+03,8.482000e+03
BAUJAHR,814.0,1.933851e+03,8.982983e+01,1.000000e+03,1.898000e+03,1.964000e+03,1.989000e+03,2.024000e+03
Spalte2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spalte3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spalte4,1.0,4.100000e+01,NaN,4.100000e+01,4.100000e+01,4.100000e+01,4.100000e+01,4.100000e+01
zus. Eigenschaften 1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fensteranzahl,120.0,3.082500e+01,3.891094e+01,0.000000e+00,2.000000e+00,2.000000e+01,4.400000e+01,2.700000e+02
Dämmungsfläche,116.0,8.620690e+00,7.048770e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+02
Stahl lm,118.0,3.207627e+01,1.262888e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+03
Fläche,116.0,5.474138e+01,1.688501e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+03
Fläche 8,118.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Fläche 9,118.0,1.614407e+01,7.110968e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.500000e+02
Holz Lm,35.0,1.177143e+02,1.687164e+02,0.000000e+00,0.000000e+00,0.000000e+00,1.900000e+02,5.000000e+02
Fläche11,26.0,2.138462e+02,5.845687e+02,0.000000e+00,0.000000e+00,0.000000e+00,3.500000e+01,2.800000e+03
Unnamed: 53,1.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
egid_gwr,814.0,7.744963e+07,9.777815e+07,1.150006e+06,1.156496e+06,2.325051e+06,2.010327e+08,2.102941e+08
baujahr_gwr,814.0,1.933851e+03,8.982983e+01,1.000000e+03,1.898000e+03,1.964000e+03,1.989000e+03,2.024000e+03
x_api,814.0,1.261901e+06,1.376119e+03,1.257211e+06,1.261160e+06,1.261822e+06,1.262834e+06,1.266320e+06
y_api,814.0,2.697371e+06,2.027500e+03,2.692379e+06,2.696020e+06,2.697281e+06,2.699195e+06,2.702513e+06
lat_api,814.0,4.750064e+01,1.244632e-02,4.745873e+01,4.749387e+01,4.749993e+01,4.750927e+01,4.753998e+01
lon_api,814.0,8.730983e+00,2.683931e-02,8.665065e+00,8.712860e+00,8.729758e+00,8.754890e+00,8.798629e+00

Deskriptive Statistik (Objekt-/Kategorie-Spalten):

,count,unique,top,freq
GSW_STATUS,814,2,bestehend,811
STRASSENNAME,814,247,Tösstalstrasse,26
HAUSNRZUSATZ,814,8,0,721
ORT,814,5,Winterthur,796
STADTKREIS,814,8,Winterthur-Stadt,226
HAUPTNUTZUNG,814,9,Verwaltungsgebäude und Gebäude mit öffentliche...,345
NUTZUNG,814,113,Wohnhaus,188
GS_EIGENTUMSKATEGORIE,814,9,Immobilien,410
GS_EIGENTUMSKAT_ZUSATZ,814,57,Wohn-& Geschäftshäuser,211
Reale Baujahr,46,24,Gesamtrenovation 2024,7
Link Google,450,439,https://www.google.com/maps/search/?api=1&quer...,4
Schadstoffen,493,3,Hohe Chance,291
Tragwerk Fassade6,724,8,Massivbau,416
Fassade Dämmung,699,3,XPS oder geklebte leichte Dämmung,472
zus. Eigenschaften 2,1,1,,1
Fassade Bekleidung,444,15,Putz,178
Konstruktion Decke,448,9,Beton konventionell,344
Bodenaufbau,666,3,Konventioneller ohne BH,488
Konstruktion Dach,447,20,Flachdach gedämmt,174
Dach Bekleidung,705,7,Flachdach gedämmt,460
Photovoltaik,709,3,NEIN,610
PV Fläche,33,6,nein,16
Fenster,749,4,Bevor 1990,523
Stahl,118,8,nein,70
Stahlblech,118,6,nein,96
Eternit,118,5,nein,109
Fläche 7,118,4,0,115
Steinplatten,118,4,nein,89
Dachziegel,118,5,nein,73
Beton,118,12,nein,70
Fläche,116,12,0,89
Speziell,117,12,nein,52
Fläche10,118,6,0,112
Holz,35,6,ja,14
Extra,117,13,normal,79
Unnamed: 52,2,2,https://meierhug.ch/projekte/wohnbauten/kastel...,1
Unnamed: 54,1,1,Grosses Potenzial,1
adresse_api,814,813,"Rennweg 5a, 8400 Winterthur",2
feature_id,814,813,192000741_0,2
label_api,814,813,Rennweg 5a <b>8400 Winterthur</b>,2
status_api,814,1,OK,814

In [119]:
# Baujahr aus der API als führende Baujahr-Spalte verwenden
df["BAUJAHR_API"] = pd.to_numeric(df["baujahr_gwr"], errors="coerce")

# Baujahr-Kategorien bilden
df["BAUJAHR_KATEGORIE"] = pd.cut(
    df["BAUJAHR_API"],
    bins=[0, 1800, 1850, 1900, 1945, 1960, 1980, 2000, 2025],
    labels=[
        "bis 1800",
        "1801-1850",
        "1851-1900",
        "1901-1945",
        "1946-1960",
        "1961-1980",
        "1981-2000",
        "2001-2024"
    ],
    include_lowest=True
)

print("Verteilung Baujahr-Kategorien:")
display(df["BAUJAHR_KATEGORIE"].value_counts(dropna=False).sort_index())

print("\nBeispielansicht:")
display(df[["EGID", "STRASSENNAME", "HAUSNR", "ORT", "BAUJAHR_API", "BAUJAHR_KATEGORIE"]].head(20))

Verteilung Baujahr-Kategorien:

BAUJAHR_KATEGORIE
bis 1800      59
1801-1850     33
1851-1900    120
1901-1945    113
1946-1960     68
1961-1980    155
1981-2000    136
2001-2024    130
Name: count, dtype: int64

Beispielansicht:

,EGID,STRASSENNAME,HAUSNR,ORT,BAUJAHR_API,BAUJAHR_KATEGORIE
0,210294075,Albert-Einstein-Strasse,1,Winterthur,2024,2001-2024
1,191993323,Schützenwiesenweg,8,Winterthur,2024,2001-2024
2,191975144,Sporrerpark,2,Winterthur,2024,2001-2024
3,191975148,Sporrerpark,5,Winterthur,2024,2001-2024
4,191975148,Sporrerpark,4,Winterthur,2024,2001-2024
5,192049948,St. Gallerstrasse,133,Winterthur,2024,2001-2024
6,210215067,Grüzefeldstrasse,34,Winterthur,2023,2001-2024
7,210261475,Guggenbühlstrasse,140,Winterthur,2023,2001-2024
8,191953253,Hörnlistrasse,31,Winterthur,2023,2001-2024
9,191953634,Im Hölderli,3,Winterthur,2023,2001-2024
10,191980305,Kiesstrasse,4,Winterthur,2023,2001-2024
11,192000741,Rennweg,5,Winterthur,2023,2001-2024
12,192000741,Rennweg,5,Winterthur,2023,2001-2024
13,192015554,Schützenstrasse,15,Winterthur,2023,2001-2024
14,192004034,Talhofweg,24,Winterthur,2023,2001-2024
15,191978341,Wurmbühlstrasse,9,Winterthur,2023,2001-2024
16,210220460,Obermühlestrasse,5,Winterthur,2022,2001-2024
17,210222195,Sulzerallee,76,Winterthur,2022,2001-2024
18,210222195,Sulzerallee,72,Winterthur,2022,2001-2024
19,210222195,Sulzerallee,74,Winterthur,2022,2001-2024

In [120]:
# Auf Gebäudeebene wechseln: pro EGID genau ein Gebäude behalten
df_buildings = (
    df.sort_values(["EGID", "STRASSENNAME", "HAUSNR"])
      .drop_duplicates(subset="EGID", keep="first")
      .reset_index(drop=True)
)

print("Anzahl Zeilen vorher:", len(df))
print("Anzahl eindeutige Gebäude nach EGID:", len(df_buildings))

# Häufigkeiten der wichtigsten Merkmale
merkmale = [
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster"
]

for merkmal in merkmale:
    print(f"\n=== Häufigkeit: {merkmal} ===")
    display(
        df_buildings[merkmal]
        .value_counts(dropna=False)
        .to_frame("Anzahl")
    )

Anzahl Zeilen vorher: 814
Anzahl eindeutige Gebäude nach EGID: 750

=== Häufigkeit: BAUJAHR_KATEGORIE ===

                   Anzahl
BAUJAHR_KATEGORIE
1961-1980             149
1981-2000             130
1851-1900             118
2001-2024             113
1901-1945             101
1946-1960              58
bis 1800               50
1801-1850              31

=== Häufigkeit: HAUPTNUTZUNG ===

                                                    Anzahl
HAUPTNUTZUNG
Verwaltungsgebäude und Gebäude mit öffentlichem...     316
Wohngebäude                                            283
Industrie und Gerwerbe                                  75
Landwirtschaft, Gärtnerei und Forstwirtschaft           26
Nebengebäude und dev.Gebäude                            17
Verkehrswesen                                           12
0                                                        9
Handel                                                   8
Gastgewerbe                                              4

=== Häufigkeit: NUTZUNG ===

                      Anzahl
NUTZUNG
Wohnhaus                 183
Schulhaus                 65
Kindergarten              44
Wohnhaus mit Schopf       25
Wohnhaus mit Scheune      18
...                      ...
Waaghaus                   1
Hangar                     1
Polizeigebäude             1
Ueberdachung               1
Kiosk                      1

[113 rows x 1 columns]

=== Häufigkeit: GS_EIGENTUMSKATEGORIE ===

                               Anzahl
GS_EIGENTUMSKATEGORIE
Immobilien                        374
Schulamt                          148
Übrige                             95
Tiefbau                            42
Sportamt                           31
Stadtgrün                          23
Kulturelles                        16
Soziales                           12
Stadtgrün–Wald und Landschaft       9

=== Häufigkeit: Fenster ===

            Anzahl
Fenster
Bevor 1990     495
Ab 1990        178
NaN             55
KEIN            20
nein             2

In [121]:
# Kategorien für die spätere Stichprobe verdichten

df_prep = df_buildings.copy()

# Fenster bereinigen
df_prep["Fenster_KATEGORIE"] = df_prep["Fenster"].copy()
df_prep["Fenster_KATEGORIE"] = df_prep["Fenster_KATEGORIE"].fillna("Unbekannt")
df_prep["Fenster_KATEGORIE"] = df_prep["Fenster_KATEGORIE"].replace({
    "nein": "KEIN",
    "Nein": "KEIN"
})

# Nutzung auf Top-Kategorien reduzieren
top_nutzung = df_prep["NUTZUNG"].value_counts().head(10).index
df_prep["NUTZUNG_KATEGORIE"] = df_prep["NUTZUNG"].where(
    df_prep["NUTZUNG"].isin(top_nutzung),
    "Sonstige"
)

# Eigentumskategorie auf wichtige Kategorien reduzieren
top_eigentum = df_prep["GS_EIGENTUMSKATEGORIE"].value_counts().head(5).index
df_prep["GS_EIGENTUMSKATEGORIE_KATEGORIE"] = df_prep["GS_EIGENTUMSKATEGORIE"].where(
    df_prep["GS_EIGENTUMSKATEGORIE"].isin(top_eigentum),
    "Sonstige"
)

# Kontrolle der verdichteten Kategorien
merkmale_reduziert = [
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE_KATEGORIE",
    "Fenster_KATEGORIE"
]

for merkmal in merkmale_reduziert:
    print(f"\n=== Verdichtete Häufigkeit: {merkmal} ===")
    display(
        df_prep[merkmal]
        .value_counts(dropna=False)
        .to_frame("Anzahl")
    )

=== Verdichtete Häufigkeit: BAUJAHR_KATEGORIE ===

                   Anzahl
BAUJAHR_KATEGORIE
1961-1980             149
1981-2000             130
1851-1900             118
2001-2024             113
1901-1945             101
1946-1960              58
bis 1800               50
1801-1850              31

=== Verdichtete Häufigkeit: HAUPTNUTZUNG ===

                                                    Anzahl
HAUPTNUTZUNG
Verwaltungsgebäude und Gebäude mit öffentlichem...     316
Wohngebäude                                            283
Industrie und Gerwerbe                                  75
Landwirtschaft, Gärtnerei und Forstwirtschaft           26
Nebengebäude und dev.Gebäude                            17
Verkehrswesen                                           12
0                                                        9
Handel                                                   8
Gastgewerbe                                              4

=== Verdichtete Häufigkeit: NUTZUNG_KATEGORIE ===

                      Anzahl
NUTZUNG_KATEGORIE
Sonstige                 339
Wohnhaus                 183
Schulhaus                 65
Kindergarten              44
Wohnhaus mit Schopf       25
Wohnhaus mit Scheune      18
Turnhalle                 16
Schulhausanlage           15
Mehrzweckgebäude          15
Gewerbehaus               15
Schulpavillon             15

=== Verdichtete Häufigkeit: GS_EIGENTUMSKATEGORIE_KATEGORIE ===

                                 Anzahl
GS_EIGENTUMSKATEGORIE_KATEGORIE
Immobilien                          374
Schulamt                            148
Übrige                               95
Sonstige                             60
Tiefbau                              42
Sportamt                             31

=== Verdichtete Häufigkeit: Fenster_KATEGORIE ===

                   Anzahl
Fenster_KATEGORIE
Bevor 1990            495
Ab 1990               178
Unbekannt              55
KEIN                   22

In [122]:
# Basis für Ground-Truth-Datensatz aufbauen

df_gt_basis = df_buildings.copy()

# 1) Nur die wichtigsten Hauptnutzungen behalten
wichtige_hauptnutzung = [
    "Verwaltungsgebäude und Gebäude mit öffentlichem Charakter",
    "Wohngebäude",
    "Industrie und Gerwerbe"
]

df_gt_basis = df_gt_basis[df_gt_basis["HAUPTNUTZUNG"].isin(wichtige_hauptnutzung)].copy()

# 2) Nur die häufigsten Eigentumskategorien behalten
wichtige_eigentum = [
    "Immobilien",
    "Schulamt",
    "Übrige",
    "Tiefbau",
    "Sportamt"
]

df_gt_basis = df_gt_basis[df_gt_basis["GS_EIGENTUMSKATEGORIE"].isin(wichtige_eigentum)].copy()

# 3) Fenster bereinigen: nur klare Kategorien behalten
df_gt_basis["Fenster_KATEGORIE"] = df_gt_basis["Fenster"].fillna("Unbekannt").replace({
    "nein": "KEIN",
    "Nein": "KEIN"
})

df_gt_basis = df_gt_basis[df_gt_basis["Fenster_KATEGORIE"].isin(["Bevor 1990", "Ab 1990", "KEIN"])].copy()

# 4) Nutzung auf Top-10 reduzieren
top_nutzung_10 = df_gt_basis["NUTZUNG"].value_counts().head(10).index
df_gt_basis["NUTZUNG_KATEGORIE"] = df_gt_basis["NUTZUNG"].where(
    df_gt_basis["NUTZUNG"].isin(top_nutzung_10),
    "Sonstige"
)

# 5) Übersicht der reduzierten Basis
print("Anzahl Gebäude in Ground-Truth-Basis:", len(df_gt_basis))

for merkmal in [
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster_KATEGORIE"
]:
    print(f"\n=== {merkmal} ===")
    display(df_gt_basis[merkmal].value_counts(dropna=False).to_frame("Anzahl"))

Anzahl Gebäude in Ground-Truth-Basis: 573

=== BAUJAHR_KATEGORIE ===

                   Anzahl
BAUJAHR_KATEGORIE
1961-1980             132
1981-2000             116
1851-1900              94
2001-2024              84
1901-1945              80
1946-1960              48
1801-1850              19
bis 1800                0

=== HAUPTNUTZUNG ===

                                                    Anzahl
HAUPTNUTZUNG
Verwaltungsgebäude und Gebäude mit öffentlichem...     258
Wohngebäude                                            242
Industrie und Gerwerbe                                  73

=== NUTZUNG_KATEGORIE ===

                     Anzahl
NUTZUNG_KATEGORIE
Sonstige                196
Wohnhaus                168
Schulhaus                64
Kindergarten             43
Wohnhaus mit Schopf      17
Schulhausanlage          15
Turnhalle                15
Gewerbehaus              15
Schulpavillon            15
Mehrzweckgebäude         13
Klubhaus                 12

=== GS_EIGENTUMSKATEGORIE ===

                       Anzahl
GS_EIGENTUMSKATEGORIE
Immobilien                302
Schulamt                  145
Übrige                     70
Sportamt                   29
Tiefbau                    27

=== Fenster_KATEGORIE ===

                   Anzahl
Fenster_KATEGORIE
Bevor 1990            407
Ab 1990               154
KEIN                   12

In [123]:
# Vorschlag für repräsentativen Ground-Truth-Datensatz (max. 15 Gebäude)

df_gt = df_gt_basis.copy()

# 1) Seltenheitsscore berechnen:
# seltene Kategorien bekommen einen höheren Score
score_spalten = [
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster_KATEGORIE"
]

for spalte in score_spalten:
    haeufigkeit = df_gt[spalte].value_counts(normalize=True)
    df_gt[f"score_{spalte}"] = df_gt[spalte].map(lambda x: 1 / haeufigkeit[x])

df_gt["DIVERSITAETS_SCORE"] = df_gt[[f"score_{s}" for s in score_spalten]].sum(axis=1)

# 2) Auswahl aufbauen
auswahl = []

# 2a) Jede Baujahr-Kategorie einmal abdecken
for kategorie in df_gt["BAUJAHR_KATEGORIE"].dropna().value_counts().index:
    kandidat = (
        df_gt[
            (df_gt["BAUJAHR_KATEGORIE"] == kategorie) &
            (~df_gt["EGID"].isin([x["EGID"] for x in auswahl]))
        ]
        .sort_values("DIVERSITAETS_SCORE", ascending=False)
        .head(1)
    )
    if not kandidat.empty:
        auswahl.append(kandidat.iloc[0].to_dict())

# 2b) Jede Hauptnutzung mindestens einmal abdecken
for kategorie in df_gt["HAUPTNUTZUNG"].dropna().value_counts().index:
    kandidat = (
        df_gt[
            (df_gt["HAUPTNUTZUNG"] == kategorie) &
            (~df_gt["EGID"].isin([x["EGID"] for x in auswahl]))
        ]
        .sort_values("DIVERSITAETS_SCORE", ascending=False)
        .head(1)
    )
    if not kandidat.empty:
        auswahl.append(kandidat.iloc[0].to_dict())

# 2c) Rest bis max. 15 mit höchstem Diversitätsscore auffüllen
bereits_gewaehlt = [x["EGID"] for x in auswahl]

rest = (
    df_gt[~df_gt["EGID"].isin(bereits_gewaehlt)]
    .sort_values("DIVERSITAETS_SCORE", ascending=False)
)

noch_noetig = 15 - len(auswahl)

if noch_noetig > 0:
    for _, row in rest.head(noch_noetig).iterrows():
        auswahl.append(row.to_dict())

# 3) Ergebnis als DataFrame
df_ground_truth = pd.DataFrame(auswahl).drop_duplicates(subset="EGID").reset_index(drop=True)

# Falls durch Überschneidungen weniger als 15 vorhanden sind, ist das okay
print("Anzahl Ground-Truth-Gebäude:", len(df_ground_truth))

display(df_ground_truth[[
    "EGID",
    "STRASSENNAME",
    "HAUSNR",
    "PLZ4",
    "ORT",
    "lat_api",
    "lon_api",
    "BAUJAHR_API",
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster_KATEGORIE",
    "DIVERSITAETS_SCORE"
]].sort_values(
    ["BAUJAHR_KATEGORIE", "HAUPTNUTZUNG", "DIVERSITAETS_SCORE"],
    ascending=[True, True, False]
))

Anzahl Ground-Truth-Gebäude: 15

C:\Users\Startklar\AppData\Local\Temp\ipykernel_20468\518668884.py:17: RuntimeWarning: divide by zero encountered in scalar divide
  df_gt[f"score_{spalte}"] = df_gt[spalte].map(lambda x: 1 / haeufigkeit[x])

,EGID,STRASSENNAME,HAUSNR,PLZ4,ORT,lat_api,lon_api,BAUJAHR_API,BAUJAHR_KATEGORIE,HAUPTNUTZUNG,NUTZUNG_KATEGORIE,GS_EIGENTUMSKATEGORIE,Fenster_KATEGORIE,DIVERSITAETS_SCORE
6,201034478,Reutlingerstrasse,78,8404,Reutlingen,47.528034,8.751361,1820,1801-1850,Verwaltungsgebäude und Gebäude mit öffentliche...,Mehrzweckgebäude,Immobilien,Bevor 1990,79.760961
2,201033848,Haldenrainstrasse,67,8404,Stadel,47.537312,8.754847,1885,1851-1900,Verwaltungsgebäude und Gebäude mit öffentliche...,Klubhaus,Übrige,Bevor 1990,65.660252
4,201032721,Barbara-Reinhart-Strasse,21,8404,Winterthur,47.504387,8.761621,1941,1901-1945,Verwaltungsgebäude und Gebäude mit öffentliche...,Mehrzweckgebäude,Immobilien,Bevor 1990,56.765567
5,201022444,St. Gallerstrasse,184,8404,Winterthur,47.497429,8.758180,1952,1946-1960,Industrie und Gerwerbe,Gewerbehaus,Übrige,Bevor 1990,67.580392
0,2323510,Scheideggstrasse,19,8400,Winterthur,47.492962,8.749986,1976,1961-1980,Verwaltungsgebäude und Gebäude mit öffentliche...,Mehrzweckgebäude,Sportamt,Bevor 1990,71.805245
1,9083693,Schützenwiesenweg,6,8400,Winterthur,47.501667,8.714010,2000,1981-2000,Verwaltungsgebäude und Gebäude mit öffentliche...,Klubhaus,Sportamt,Ab 1990,78.389985
13,210145963,Hegistrasse,41,8404,Winterthur,47.503983,8.756852,1994,1981-2000,Verwaltungsgebäude und Gebäude mit öffentliche...,Sonstige,Sportamt,KEIN,77.592675
14,201032839,Radhofstrasse,6,8408,Winterthur,47.518597,8.690289,1990,1981-2000,Verwaltungsgebäude und Gebäude mit öffentliche...,Klubhaus,Sportamt,Bevor 1990,76.077069
3,201028650,Auwiesenstrasse,49,8406,Winterthur,47.482769,8.704549,2011,2001-2024,Industrie und Gerwerbe,Sonstige,Tiefbau,KEIN,86.566435
9,201036423,Harzachstrasse,2,8404,Winterthur,47.494965,8.763764,2008,2001-2024,Industrie und Gerwerbe,Sonstige,Tiefbau,KEIN,86.566435
12,210294075,Albert-Einstein-Strasse,1,8404,Winterthur,47.515961,8.766397,2024,2001-2024,Industrie und Gerwerbe,Gewerbehaus,Tiefbau,Ab 1990,77.813745
7,192000741,Rennweg,5,8400,Winterthur,47.500774,8.716507,2023,2001-2024,Verwaltungsgebäude und Gebäude mit öffentliche...,Klubhaus,Sportamt,Ab 1990,80.271759
10,191993323,Schützenwiesenweg,8,8400,Winterthur,47.500713,8.714772,2024,2001-2024,Verwaltungsgebäude und Gebäude mit öffentliche...,Klubhaus,Sportamt,Ab 1990,80.271759
11,191980305,Kiesstrasse,4,8400,Winterthur,47.506710,8.724996,2023,2001-2024,Verwaltungsgebäude und Gebäude mit öffentliche...,Mehrzweckgebäude,Tiefbau,Ab 1990,78.062283
8,210183499,Espenstrasse,18,8408,Winterthur,47.507442,8.681062,2011,2001-2024,Wohngebäude,Sonstige,Schulamt,KEIN,63.814391

In [124]:
# Repräsentativität der 15 Ground-Truth-Gebäude prüfen
# und Score-Berechnung robuster machen

df_gt_check = df_gt_basis.copy()

score_spalten = [
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster_KATEGORIE"
]

# Robuste Score-Berechnung: nur tatsächlich vorkommende Kategorien verwenden
for spalte in score_spalten:
    haeufigkeit = df_gt_check[spalte].astype(str).value_counts(normalize=True)
    df_gt_check[f"score_{spalte}"] = df_gt_check[spalte].astype(str).map(
        lambda x: 1 / haeufigkeit[x] if haeufigkeit[x] > 0 else 0
    )

df_gt_check["DIVERSITAETS_SCORE"] = df_gt_check[[f"score_{s}" for s in score_spalten]].sum(axis=1)

# Die bereits ausgewählten EGIDs mit der Basis verknüpfen
df_ground_truth_check = df_gt_check[df_gt_check["EGID"].isin(df_ground_truth["EGID"])].copy()

# Vergleich der Verteilungen: Gesamtbasis vs. Ground-Truth
vergleich_spalten = [
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster_KATEGORIE"
]

for spalte in vergleich_spalten:
    print(f"\n=== Vergleich: {spalte} ===")
    
    gesamt = (
        df_gt_check[spalte]
        .astype(str)
        .value_counts(normalize=True)
        .rename("Gesamtanteil")
    )
    
    gt = (
        df_ground_truth_check[spalte]
        .astype(str)
        .value_counts(normalize=True)
        .rename("GT_Anteil")
    )
    
    vergleich = pd.concat([gesamt, gt], axis=1).fillna(0)
    vergleich["Differenz"] = vergleich["GT_Anteil"] - vergleich["Gesamtanteil"]
    
    display(vergleich.sort_values("Gesamtanteil", ascending=False))

=== Vergleich: BAUJAHR_KATEGORIE ===

                   Gesamtanteil  GT_Anteil  Differenz
BAUJAHR_KATEGORIE
1961-1980              0.230366   0.066667  -0.163700
1981-2000              0.202443   0.200000  -0.002443
1851-1900              0.164049   0.066667  -0.097382
2001-2024              0.146597   0.466667   0.320070
1901-1945              0.139616   0.066667  -0.072949
1946-1960              0.083770   0.066667  -0.017103
1801-1850              0.033159   0.066667   0.033508

=== Vergleich: HAUPTNUTZUNG ===

,Gesamtanteil,GT_Anteil,Differenz
HAUPTNUTZUNG,,,
Verwaltungsgebäude und Gebäude mit öffentlichem Charakter,0.450262,0.666667,0.216405
Wohngebäude,0.422339,0.066667,-0.355672
Industrie und Gerwerbe,0.127400,0.266667,0.139267

=== Vergleich: NUTZUNG_KATEGORIE ===

                     Gesamtanteil  GT_Anteil  Differenz
NUTZUNG_KATEGORIE
Sonstige                 0.342059   0.266667  -0.075393
Wohnhaus                 0.293194   0.000000  -0.293194
Schulhaus                0.111693   0.000000  -0.111693
Kindergarten             0.075044   0.000000  -0.075044
Wohnhaus mit Schopf      0.029668   0.000000  -0.029668
Schulhausanlage          0.026178   0.000000  -0.026178
Turnhalle                0.026178   0.000000  -0.026178
Gewerbehaus              0.026178   0.133333   0.107155
Schulpavillon            0.026178   0.000000  -0.026178
Mehrzweckgebäude         0.022688   0.266667   0.243979
Klubhaus                 0.020942   0.333333   0.312391

=== Vergleich: GS_EIGENTUMSKATEGORIE ===

                       Gesamtanteil  GT_Anteil  Differenz
GS_EIGENTUMSKATEGORIE
Immobilien                 0.527051   0.133333  -0.393717
Schulamt                   0.253054   0.066667  -0.186387
Übrige                     0.122164   0.133333   0.011169
Sportamt                   0.050611   0.400000   0.349389
Tiefbau                    0.047120   0.266667   0.219546

=== Vergleich: Fenster_KATEGORIE ===

                   Gesamtanteil  GT_Anteil  Differenz
Fenster_KATEGORIE
Bevor 1990             0.710297   0.400000  -0.310297
Ab 1990                0.268761   0.333333   0.064572
KEIN                   0.020942   0.266667   0.245724

In [125]:
# Neue, repräsentativere Auswahl mit proportionalen Quoten
df_basis = df_gt_basis.copy()

# Hilfsfunktion: proportionale Zielanzahlen mit Largest-Remainder-Methode
def allocate_counts(series, total_n):
    anteile = series.value_counts(normalize=True)
    raw = anteile * total_n
    basis = np.floor(raw).astype(int)
    rest = raw - basis

    fehlend = total_n - basis.sum()
    if fehlend > 0:
        for idx in rest.sort_values(ascending=False).index[:fehlend]:
            basis[idx] += 1

    return basis[basis > 0]

# 1) Quoten nach HAUPTNUTZUNG für insgesamt 15 Gebäude
ziel_anzahl = 15
quoten_hauptnutzung = allocate_counts(df_basis["HAUPTNUTZUNG"], ziel_anzahl)

print("Quoten HAUPTNUTZUNG:")
display(quoten_hauptnutzung.to_frame("Zielanzahl"))

auswahl_rows = []
bereits_gewaehlt = set()

# 2) Innerhalb jeder Hauptnutzung proportional nach BAUJAHR_KATEGORIE sampeln
for hauptnutzung, n_haupt in quoten_hauptnutzung.items():
    teilmenge_h = df_basis[df_basis["HAUPTNUTZUNG"] == hauptnutzung].copy()

    quoten_baujahr = allocate_counts(teilmenge_h["BAUJAHR_KATEGORIE"], n_haupt)

    for baujahr_kat, n_baujahr in quoten_baujahr.items():
        kandidaten = teilmenge_h[
            (teilmenge_h["BAUJAHR_KATEGORIE"] == baujahr_kat) &
            (~teilmenge_h["EGID"].isin(bereits_gewaehlt))
        ].copy()

        if len(kandidaten) == 0:
            continue

        sample_n = min(n_baujahr, len(kandidaten))
        sample = kandidaten.sample(n=sample_n, random_state=42)

        auswahl_rows.append(sample)
        bereits_gewaehlt.update(sample["EGID"].tolist())

# 3) Falls wir wegen knapper Kombinationen noch unter 15 sind: aus Rest auffüllen
df_ground_truth_v2 = pd.concat(auswahl_rows, ignore_index=True) if auswahl_rows else pd.DataFrame()

if len(df_ground_truth_v2) < ziel_anzahl:
    rest = df_basis[~df_basis["EGID"].isin(df_ground_truth_v2["EGID"])].copy()
    noch_noetig = ziel_anzahl - len(df_ground_truth_v2)

    if len(rest) > 0:
        extra = rest.sample(n=min(noch_noetig, len(rest)), random_state=42)
        df_ground_truth_v2 = pd.concat([df_ground_truth_v2, extra], ignore_index=True)

# 4) Sicherheitshalber deduplizieren
df_ground_truth_v2 = df_ground_truth_v2.drop_duplicates(subset="EGID").reset_index(drop=True)

print("Anzahl Ground-Truth-Gebäude (v2):", len(df_ground_truth_v2))

display(df_ground_truth_v2[[
    "EGID",
    "STRASSENNAME",
    "HAUSNR",
    "PLZ4",
    "ORT",
    "lat_api",
    "lon_api",
    "BAUJAHR_API",
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster_KATEGORIE"
]].sort_values(["HAUPTNUTZUNG", "BAUJAHR_API"]))

Quoten HAUPTNUTZUNG:

                                                    Zielanzahl
HAUPTNUTZUNG
Verwaltungsgebäude und Gebäude mit öffentlichem...           7
Wohngebäude                                                  6
Industrie und Gerwerbe                                       2

Anzahl Ground-Truth-Gebäude (v2): 15

,EGID,STRASSENNAME,HAUSNR,PLZ4,ORT,lat_api,lon_api,BAUJAHR_API,BAUJAHR_KATEGORIE,HAUPTNUTZUNG,NUTZUNG_KATEGORIE,GS_EIGENTUMSKATEGORIE,Fenster_KATEGORIE
14,2326354,Stegackerstrasse,14,8409,Winterthur,47.501804,8.773801,1993,1981-2000,Industrie und Gerwerbe,Gewerbehaus,Immobilien,Ab 1990
13,210215443,Burgstrasse,66,8408,Winterthur,47.507259,8.693533,2017,2001-2024,Industrie und Gerwerbe,Sonstige,Übrige,Ab 1990
4,201033071,St.-Georgen-Strasse,69,8400,Winterthur,47.502357,8.731490,1869,1851-1900,Verwaltungsgebäude und Gebäude mit öffentliche...,Turnhalle,Schulamt,Bevor 1990
6,2327006,Stadlerstrasse,54,8404,Winterthur,47.512737,8.758281,1945,1901-1945,Verwaltungsgebäude und Gebäude mit öffentliche...,Kindergarten,Schulamt,Bevor 1990
5,201033870,Mattenbachstrasse,3,8400,Winterthur,47.494606,8.736107,1960,1946-1960,Verwaltungsgebäude und Gebäude mit öffentliche...,Schulhaus,Schulamt,Bevor 1990
0,2323612,Tösstalstrasse,54,8400,Winterthur,47.495716,8.736517,1962,1961-1980,Verwaltungsgebäude und Gebäude mit öffentliche...,Sonstige,Immobilien,Bevor 1990
1,1150227,Neumarkt,4,8400,Winterthur,47.498436,8.726647,1965,1961-1980,Verwaltungsgebäude und Gebäude mit öffentliche...,Sonstige,Immobilien,Bevor 1990
2,201033613,Kehrackerstrasse,7,8400,Winterthur,47.493271,8.733987,1993,1981-2000,Verwaltungsgebäude und Gebäude mit öffentliche...,Sonstige,Immobilien,Ab 1990
3,210219967,Büelhofstrasse,32,8405,Winterthur,47.483540,8.764112,2018,2001-2024,Verwaltungsgebäude und Gebäude mit öffentliche...,Schulhaus,Schulamt,Ab 1990
8,1161614,Reitweg,12,8400,Winterthur,47.494160,8.732731,1863,1851-1900,Wohngebäude,Wohnhaus,Immobilien,Bevor 1990
7,1152552,Ackeretstrasse,17,8400,Winterthur,47.503185,8.716382,1897,1851-1900,Wohngebäude,Wohnhaus,Immobilien,Bevor 1990
9,1151523,Lärchenstrasse,45,8400,Winterthur,47.491714,8.719482,1908,1901-1945,Wohngebäude,Wohnhaus,Immobilien,Bevor 1990
10,1154336,Pappelweg,26,8404,Winterthur,47.514202,8.761744,1964,1961-1980,Wohngebäude,Wohnhaus,Immobilien,Bevor 1990
11,1156499,Hölzliweg,8,8405,Winterthur,47.485893,8.770424,1983,1981-2000,Wohngebäude,Wohnhaus mit Schopf,Immobilien,Bevor 1990
12,191975148,Sporrerpark,4,8408,Winterthur,47.518089,8.692179,2024,2001-2024,Wohngebäude,Wohnhaus,Immobilien,Ab 1990

In [126]:
# Repräsentativität der neuen Auswahl (v2) prüfen

vergleich_spalten = [
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster_KATEGORIE"
]

for spalte in vergleich_spalten:
    print(f"\n=== Vergleich v2: {spalte} ===")

    gesamt = (
        df_gt_basis[spalte]
        .astype(str)
        .value_counts(normalize=True)
        .rename("Gesamtanteil")
    )

    gt = (
        df_ground_truth_v2[spalte]
        .astype(str)
        .value_counts(normalize=True)
        .rename("GT_Anteil")
    )

    vergleich = pd.concat([gesamt, gt], axis=1).fillna(0)
    vergleich["Differenz"] = vergleich["GT_Anteil"] - vergleich["Gesamtanteil"]

    display(vergleich.sort_values("Gesamtanteil", ascending=False))

=== Vergleich v2: BAUJAHR_KATEGORIE ===

                   Gesamtanteil  GT_Anteil  Differenz
BAUJAHR_KATEGORIE
1961-1980              0.230366   0.200000  -0.030366
1981-2000              0.202443   0.200000  -0.002443
1851-1900              0.164049   0.200000   0.035951
2001-2024              0.146597   0.200000   0.053403
1901-1945              0.139616   0.133333  -0.006283
1946-1960              0.083770   0.066667  -0.017103
1801-1850              0.033159   0.000000  -0.033159

=== Vergleich v2: HAUPTNUTZUNG ===

,Gesamtanteil,GT_Anteil,Differenz
HAUPTNUTZUNG,,,
Verwaltungsgebäude und Gebäude mit öffentlichem Charakter,0.450262,0.466667,0.016405
Wohngebäude,0.422339,0.400000,-0.022339
Industrie und Gerwerbe,0.127400,0.133333,0.005934

=== Vergleich v2: NUTZUNG_KATEGORIE ===

                     Gesamtanteil  GT_Anteil  Differenz
NUTZUNG_KATEGORIE
Sonstige                 0.342059   0.266667  -0.075393
Wohnhaus                 0.293194   0.333333   0.040140
Schulhaus                0.111693   0.133333   0.021640
Kindergarten             0.075044   0.066667  -0.008377
Wohnhaus mit Schopf      0.029668   0.066667   0.036998
Schulhausanlage          0.026178   0.000000  -0.026178
Turnhalle                0.026178   0.066667   0.040489
Gewerbehaus              0.026178   0.066667   0.040489
Schulpavillon            0.026178   0.000000  -0.026178
Mehrzweckgebäude         0.022688   0.000000  -0.022688
Klubhaus                 0.020942   0.000000  -0.020942

=== Vergleich v2: GS_EIGENTUMSKATEGORIE ===

                       Gesamtanteil  GT_Anteil  Differenz
GS_EIGENTUMSKATEGORIE
Immobilien                 0.527051   0.666667   0.139616
Schulamt                   0.253054   0.266667   0.013613
Übrige                     0.122164   0.066667  -0.055497
Sportamt                   0.050611   0.000000  -0.050611
Tiefbau                    0.047120   0.000000  -0.047120

=== Vergleich v2: Fenster_KATEGORIE ===

                   Gesamtanteil  GT_Anteil  Differenz
Fenster_KATEGORIE
Bevor 1990             0.710297   0.666667  -0.043630
Ab 1990                0.268761   0.333333   0.064572
KEIN                   0.020942   0.000000  -0.020942

In [127]:
from pathlib import Path

# Finale Ground-Truth-Tabelle aufbereiten
df_ground_truth_final = df_ground_truth_v2.copy()

# Vollständige Adresse ergänzen
df_ground_truth_final["ADRESSE"] = (
    df_ground_truth_final["STRASSENNAME"].astype(str).str.strip()
    + " "
    + df_ground_truth_final["HAUSNR"].astype(str).str.strip()
    + ", "
    + df_ground_truth_final["ORT"].astype(str).str.strip()
)

# Relevante Spalten auswählen und sortieren
df_ground_truth_final = df_ground_truth_final[[
    "EGID",
    "ADRESSE",
    "STRASSENNAME",
    "HAUSNR",
    "PLZ4",
    "ORT",
    "lat_api",
    "lon_api",
    "BAUJAHR_API",
    "BAUJAHR_KATEGORIE",
    "HAUPTNUTZUNG",
    "NUTZUNG_KATEGORIE",
    "GS_EIGENTUMSKATEGORIE",
    "Fenster_KATEGORIE"
]].sort_values(
    ["HAUPTNUTZUNG", "BAUJAHR_API", "ADRESSE"]
).reset_index(drop=True)

print("Finale Anzahl Ground-Truth-Gebäude:", len(df_ground_truth_final))
display(df_ground_truth_final)

Finale Anzahl Ground-Truth-Gebäude: 15

,EGID,ADRESSE,STRASSENNAME,HAUSNR,PLZ4,ORT,lat_api,lon_api,BAUJAHR_API,BAUJAHR_KATEGORIE,HAUPTNUTZUNG,NUTZUNG_KATEGORIE,GS_EIGENTUMSKATEGORIE,Fenster_KATEGORIE
0,2326354,"Stegackerstrasse 14, Winterthur",Stegackerstrasse,14,8409,Winterthur,47.501804,8.773801,1993,1981-2000,Industrie und Gerwerbe,Gewerbehaus,Immobilien,Ab 1990
1,210215443,"Burgstrasse 66, Winterthur",Burgstrasse,66,8408,Winterthur,47.507259,8.693533,2017,2001-2024,Industrie und Gerwerbe,Sonstige,Übrige,Ab 1990
2,201033071,"St.-Georgen-Strasse 69, Winterthur",St.-Georgen-Strasse,69,8400,Winterthur,47.502357,8.731490,1869,1851-1900,Verwaltungsgebäude und Gebäude mit öffentliche...,Turnhalle,Schulamt,Bevor 1990
3,2327006,"Stadlerstrasse 54, Winterthur",Stadlerstrasse,54,8404,Winterthur,47.512737,8.758281,1945,1901-1945,Verwaltungsgebäude und Gebäude mit öffentliche...,Kindergarten,Schulamt,Bevor 1990
4,201033870,"Mattenbachstrasse 3, Winterthur",Mattenbachstrasse,3,8400,Winterthur,47.494606,8.736107,1960,1946-1960,Verwaltungsgebäude und Gebäude mit öffentliche...,Schulhaus,Schulamt,Bevor 1990
5,2323612,"Tösstalstrasse 54, Winterthur",Tösstalstrasse,54,8400,Winterthur,47.495716,8.736517,1962,1961-1980,Verwaltungsgebäude und Gebäude mit öffentliche...,Sonstige,Immobilien,Bevor 1990
6,1150227,"Neumarkt 4, Winterthur",Neumarkt,4,8400,Winterthur,47.498436,8.726647,1965,1961-1980,Verwaltungsgebäude und Gebäude mit öffentliche...,Sonstige,Immobilien,Bevor 1990
7,201033613,"Kehrackerstrasse 7, Winterthur",Kehrackerstrasse,7,8400,Winterthur,47.493271,8.733987,1993,1981-2000,Verwaltungsgebäude und Gebäude mit öffentliche...,Sonstige,Immobilien,Ab 1990
8,210219967,"Büelhofstrasse 32, Winterthur",Büelhofstrasse,32,8405,Winterthur,47.483540,8.764112,2018,2001-2024,Verwaltungsgebäude und Gebäude mit öffentliche...,Schulhaus,Schulamt,Ab 1990
9,1161614,"Reitweg 12, Winterthur",Reitweg,12,8400,Winterthur,47.494160,8.732731,1863,1851-1900,Wohngebäude,Wohnhaus,Immobilien,Bevor 1990
10,1152552,"Ackeretstrasse 17, Winterthur",Ackeretstrasse,17,8400,Winterthur,47.503185,8.716382,1897,1851-1900,Wohngebäude,Wohnhaus,Immobilien,Bevor 1990
11,1151523,"Lärchenstrasse 45, Winterthur",Lärchenstrasse,45,8400,Winterthur,47.491714,8.719482,1908,1901-1945,Wohngebäude,Wohnhaus,Immobilien,Bevor 1990
12,1154336,"Pappelweg 26, Winterthur",Pappelweg,26,8404,Winterthur,47.514202,8.761744,1964,1961-1980,Wohngebäude,Wohnhaus,Immobilien,Bevor 1990
13,1156499,"Hölzliweg 8, Winterthur",Hölzliweg,8,8405,Winterthur,47.485893,8.770424,1983,1981-2000,Wohngebäude,Wohnhaus mit Schopf,Immobilien,Bevor 1990
14,191975148,"Sporrerpark 4, Winterthur",Sporrerpark,4,8408,Winterthur,47.518089,8.692179,2024,2001-2024,Wohngebäude,Wohnhaus,Immobilien,Ab 1990

In [128]:
# Export in den Data-Ordner
data_dir = Path("Data")
data_dir.mkdir(exist_ok=True)

output_path = data_dir / "03_Ground_Truth_Datensatz.xlsx"
df_ground_truth_final.to_excel(output_path, index=False)

print(f"Gespeichert: {output_path}")

Gespeichert: Data\03_Ground_Truth_Datensatz.xlsx